# These config values will be shared by all environments but can be overridden.
common: &common
  client_id: 'faceruby-ms'
  brokers:
    - localhost:9092

development:
  <<: *common

test:
  <<: *common

staging:
  <<: *common

production:
  <<: *common
